I finished the assignment.
yuki-sato-0402/PFMCPP_Project2 pull request #1
Opened 2022-11-05 15:48 UTC by yuki-sato-0402

2022-11-07 20:14 UTC, matkatmusic requested changes
Your submission is OK, excluding the code formatting issues marked below

2022-11-07 20:14 UTC, matkatmusic commented on main.cpp
> +    ignoreUnused(number,num,num2,num3,num4,num5,num6,A,B,C,num7,num8,num9,chr1,chr2,chr3,num10,num11,num12); //passing each variable declared to the ignoreUnused() function
It is important to be consistent when formatting your code.
The coding style for this course asks that you add a space after all commas.
- [ ] revise

2022-11-07 20:14 UTC, matkatmusic commented on main.cpp
> +    ignoreUnused(num1, num2 );
It is important to be consistent when formatting your code.
parentheses should not have spaces on either side of them.
```
int num(int num1 = 1, int num2 = 2)
{
    ignoreUnused(num1, num2); 
```
- [ ] revise

2022-11-07 20:14 UTC, matkatmusic commented on main.cpp
> +    return{};
Code style:
- put spaces around `=`
- commas should have a space after them, not before them.
- parentheses should not have spaces on either side of them.

- [ ] revise

2022-11-07 20:14 UTC, matkatmusic commented on main.cpp
> +    ignoreUnused(dog, cat );
Code style:
- parentheses should not have spaces on either side of them.

- [ ] revise

2022-11-07 20:14 UTC, matkatmusic commented on main.cpp
> +    ignoreUnused(score1, score2 );
Code style:
- put spaces around `=`
- commas should have a space after them, not before them.
- parentheses should not have spaces on either side of them.

- [ ] revise

2022-11-07 20:14 UTC, matkatmusic commented on main.cpp
> +    ignoreUnused(money, gold );
Code style:
- put spaces around `=`
- commas should have a space after them, not before them.
- parentheses should not have spaces on either side of them.

- [ ] revise

2022-11-07 20:14 UTC, matkatmusic commented on main.cpp
> +    ignoreUnused(num3, num4 );
Code style:
- put spaces around `=`
- commas should have a space after them, not before them.
- parentheses should not have spaces on either side of them.

- [ ] revise

2022-11-07 20:14 UTC, matkatmusic commented on main.cpp
> +    ignoreUnused(num5, num6 );
Code style:
- put spaces around `=`
- commas should have a space after them, not before them.
- parentheses should not have spaces on either side of them.

- [ ] revise

2022-11-07 20:14 UTC, matkatmusic commented on main.cpp
> +    ignoreUnused(chr1, chr2 );
Code style:
- put spaces around `=`
- commas should have a space after them, not before them.
- parentheses should not have spaces on either side of them.

- [ ] revise

2022-11-07 20:14 UTC, matkatmusic commented on main.cpp
> +    ignoreUnused(pricePerUnitOfArea, landSize );
Code style:
- put spaces around `=`
- commas should have a space after them, not before them.
- parentheses should not have spaces on either side of them.

- [ ] revise

2022-11-07 20:14 UTC, matkatmusic commented on main.cpp
> +    ignoreUnused(distance,fuelConsumption );
Code style:
- put spaces around `=`
- commas should have a space after them, not before them.
- parentheses should not have spaces on either side of them.

- [ ] revise

2022-11-07 20:14 UTC, matkatmusic commented on main.cpp
> +    ignoreUnused(carRented,count,purchase,animals,compare,whichIsExpensive,calaculated,printNum, printChar,autoLand,car);
Code style:
- put spaces around `=`
- commas should have a space after them, not before them.
- parentheses should not have spaces on either side of them.

- [ ] revise

2022-11-08 00:52 UTC, yuki-sato-0402 commented on main.cpp
> +    ignoreUnused(carRented,count,purchase,animals,compare,whichIsExpensive,calaculated,printNum, printChar,autoLand,car);
I have not been able to correct this issue.

2022-11-08 02:37 UTC, matkatmusic approved these changes

2022-11-08 02:38 UTC, merged